// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rpc_update_merchant_order_status.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMerchantOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantOrderId int64       `protobuf:"varint,1,opt,name=merchant_order_id,json=merchantOrderId,proto3" json:"merchant_order_id,omitempty"`
	Status          OrderStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.OrderStatus" json:"status,omitempty"`
}

func (x *UpdateMerchantOrderReq) Reset() {
	*x = UpdateMerchantOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_update_merchant_order_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchantOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantOrderReq) ProtoMessage() {}

func (x *UpdateMerchantOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_merchant_order_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantOrderReq.ProtoReflect.Descriptor instead.
func (*UpdateMerchantOrderReq) Descriptor() ([]byte, []int) {
	return file_rpc_update_merchant_order_status_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateMerchantOrderReq) GetMerchantOrderId() int64 {
	if x != nil {
		return x.MerchantOrderId
	}
	return 0
}

func (x *UpdateMerchantOrderReq) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_OPEN
}

type UpdateMerchantOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantOrder *MerchantOrder `protobuf:"bytes,1,opt,name=merchant_order,json=merchantOrder,proto3" json:"merchant_order,omitempty"`
}

func (x *UpdateMerchantOrderResponse) Reset() {
	*x = UpdateMerchantOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_update_merchant_order_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMerchantOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMerchantOrderResponse) ProtoMessage() {}

func (x *UpdateMerchantOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_update_merchant_order_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMerchantOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateMerchantOrderResponse) Descriptor() ([]byte, []int) {
	return file_rpc_update_merchant_order_status_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMerchantOrderResponse) GetMerchantOrder() *MerchantOrder {
	if x != nil {
		return x.MerchantOrder
	}
	return nil
}

var File_rpc_update_merchant_order_status_proto protoreflect.FileDescriptor

var file_rpc_update_merchant_order_status_proto_rawDesc = []byte{
	0x0a, 0x26, 0x72, 0x70, 0x63, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x18, 0x72, 0x70,
	0x63, 0x5f, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x5f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x57, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x0d, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x72,
	0x6e, 0x69, 0x65, 0x2d, 0x70, 0x68, 0x61, 0x6d, 0x2f, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72,
	0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_update_merchant_order_status_proto_rawDescOnce sync.Once
	file_rpc_update_merchant_order_status_proto_rawDescData = file_rpc_update_merchant_order_status_proto_rawDesc
)

func file_rpc_update_merchant_order_status_proto_rawDescGZIP() []byte {
	file_rpc_update_merchant_order_status_proto_rawDescOnce.Do(func() {
		file_rpc_update_merchant_order_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_update_merchant_order_status_proto_rawDescData)
	})
	return file_rpc_update_merchant_order_status_proto_rawDescData
}

var file_rpc_update_merchant_order_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_update_merchant_order_status_proto_goTypes = []interface{}{
	(*UpdateMerchantOrderReq)(nil),      // 0: pb.UpdateMerchantOrderReq
	(*UpdateMerchantOrderResponse)(nil), // 1: pb.UpdateMerchantOrderResponse
	(OrderStatus)(0),                    // 2: pb.OrderStatus
	(*MerchantOrder)(nil),               // 3: pb.MerchantOrder
}
var file_rpc_update_merchant_order_status_proto_depIdxs = []int32{
	2, // 0: pb.UpdateMerchantOrderReq.status:type_name -> pb.OrderStatus
	3, // 1: pb.UpdateMerchantOrderResponse.merchant_order:type_name -> pb.MerchantOrder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_update_merchant_order_status_proto_init() }
func file_rpc_update_merchant_order_status_proto_init() {
	if File_rpc_update_merchant_order_status_proto != nil {
		return
	}
	file_rpc_merchant_order_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_update_merchant_order_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMerchantOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_update_merchant_order_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMerchantOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_update_merchant_order_status_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_update_merchant_order_status_proto_goTypes,
		DependencyIndexes: file_rpc_update_merchant_order_status_proto_depIdxs,
		MessageInfos:      file_rpc_update_merchant_order_status_proto_msgTypes,
	}.Build()
	File_rpc_update_merchant_order_status_proto = out.File
	file_rpc_update_merchant_order_status_proto_rawDesc = nil
	file_rpc_update_merchant_order_status_proto_goTypes = nil
	file_rpc_update_merchant_order_status_proto_depIdxs = nil
}
